import { NextResponse } from "next/server";
import { dbConnect } from "@/lib/mongodb";
import { getToken } from "next-auth/jwt";
import { HostelMember } from "@/models/HostelMember";
import { HostelPayment } from "@/models/HostelPayment";
import { HostelLog } from "@/models/HostelLog";
import { HostelAnalytics } from "@/models/HostelAnalytics";
import mongoose from "mongoose";

export const dynamic = "force-dynamic";

// POST /api/hostel/members/[id]/vacate
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
    try {
        const [token, { id }] = await Promise.all([getToken({ req: req as any }), params]);
        await dbConnect();
        
        if (!token || token.role !== "hostel_admin") {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }
        
        const hostelId = token.hostelId as string;

        const body = await req.json();
        const settleAmount = Number(body.settleAmount) || 0;
        if (!Number.isFinite(settleAmount) || Math.abs(settleAmount) > 9_999_999_999) {
             return NextResponse.json({ error: "Invalid settlement amount boundary" }, { status: 400 });
        }

        const settleMode = body.settleMode || "cash";

        const member = await HostelMember.findOne({ _id: id, hostelId, isDeleted: false });
        if (!member) {
            return NextResponse.json({ error: "Member not found" }, { status: 404 });
        }

        if (member.status === "vacated") {
            return NextResponse.json({ error: "Member is already vacated" }, { status: 400 });
        }

        const finalCheck = member.balance + settleAmount;
        if (Math.abs(finalCheck) >= 1) { 
            return NextResponse.json({ 
                error: `Final balance must perfectly equal 0. Current balance: ${member.balance}, but settle parameter provided: ${settleAmount}` 
            }, { status: 400 });
        }

        const now = new Date();
        const yearMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;

        if (Math.abs(settleAmount) > 0) {
            const isRefund = settleAmount < 0;
            const absoluteAmount = Math.abs(settleAmount);
            const paymentType = isRefund ? "refund" : "settlement";

            await HostelPayment.create({
                hostelId,
                memberId: member._id,
                planId: member.planId,
                amount: absoluteAmount,
                paymentMethod: settleMode,
                notes: `Autogenerated ${paymentType} to zero balance during account vacation.`,
                paymentType: paymentType,
                status: "success",
                idempotencyKey: body.idempotencyKey
            });

            await HostelAnalytics.updateOne(
                { hostelId, yearMonth },
                { $inc: { totalIncome: settleAmount, checkedOutMembers: 1 } },
                { upsert: true }
            );
        } else {
             await HostelAnalytics.updateOne(
                { hostelId, yearMonth },
                { $inc: { checkedOutMembers: 1 } },
                { upsert: true }
            );
        }

        member.status = "vacated";
        member.isActive = false; 
        member.balance = 0;      
        member.vacated_at = now;
        
        await member.save();
        
        await HostelLog.create({
            hostelId,
            type: "status_update",
            memberId: member.memberId,
            memberObjectId: member._id,
            memberName: member.name,
            description: `Member ${member.name} (${member.memberId}) vacated their room. Rent cycle stopped. Settled amount: ₹${settleAmount}`,
            performedBy: token.email as string,
        });

        return NextResponse.json({ success: true, member });
    } catch (error: any) {
        if (error?.code === 11000 && error?.keyPattern?.idempotencyKey) {
            return NextResponse.json({ message: "Duplicate vacate processed safely", success: true }, { status: 200 });
        }
        console.error("[POST /api/hostel/members/[id]/vacate]", error);
        return NextResponse.json({ error: error?.message || "Server error" }, { status: 500 });
    }
}
